Changes to download correct version of buildtools nativesdk
Source: MontaVista Software, LLC
MR: 00000
Type: Defect Fix
Disposition: Local
ChangeID: ea4feccc86ec1cf7038f87e54c4de0bd651e0da6
Description:

Using 2.6.x buildtools nativesdk installer solves below error,
-- snip --
Your system needs to support the en_US.UTF-8 locale
-- snip --

Check out thud branch of meta-selinux, it solves below error;
-- snip --
configure: error: unrecognized option: `-Dselinux=false'
Try `../glib-2.58.0/configure --help' for more information
NOTE:
ERROR: configure failed
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>